### ISSUE TITLE
how to compile example?

### ISSUE THREAD

**Issue by dadahua555** [wiedi/libvirt#1]
I just want to study the api of libvirt, so I hope to compile and run the code in example， would someone tell me how to complie hellolibvirt and domain-events?

**Comment by wiedi** [comment]
The normal build process should build the examples too:
```
$ ./configure --prefix=$HOME/usr
$ make
$ make install
```

Please note that this is not the official libvirt repo. This is my old workspace and has not been updates in a long time. Please use https://github.com/libvirt/libvirt or https://libvirt.org/git/?p=libvirt.git

**Comment by dadahua555** [comment]
> The normal build process should build the examples too:
> 
> ```
> $ ./configure --prefix=$HOME/usr
> $ make
> $ make install
> ```
> 
> Please note that this is not the official libvirt repo. This is my old workspace and has not been updates in a long time. Please use https://github.com/libvirt/libvirt or https://libvirt.org/git/?p=libvirt.git

thanks a lot!
